### ISSUE TITLE
Gem doesn't include all the relevant files

### ISSUE THREAD

**Issue by cpence** [stuyam/bootstrap-email#14]
The bundled version of the gem doesn't have all of the stylesheets required to build. See the below:

```
cpence@osgood ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootstrap-email-0.2.2 $ ls -R
.:
VERSION  lib/

./lib:
bootstrap-email/  bootstrap-email.rb

./lib/bootstrap-email:
action_mailer.rb  engine.rb  premailer_railtie.rb  version.rb
```

**Comment by cpence** [comment]
If people stumble on this ticket in the meantime, you can work around it by using the github source for the gem rather than the packaged version, which works great. (And produces really nice emails!)

**Comment by stuyam** [comment]
This is fixed in the latest release: https://github.com/stuyam/bootstrap-email/releases/tag/0.2.3, should all work now. Let me know how that works for you @cpence!

**Comment by cpence** [comment]
Works perfectly, thanks!
