### ISSUE TITLE
ActionView::Template::Error: Invalid CSS after

### ISSUE THREAD

**Issue by genkin-he** [stuyam/bootstrap-email#16]
thanks for your work! I got this error when i sending an email, could you give me some help?
```
ActionView::Template::Error: Invalid CSS after "...ings-ratios: (1": expected ")", was ": 2.25, 2: 2, 3..."
```
thanks again

**Comment by JacobGalati** [comment]
@genkin-he I know this was a long time ago, but I'm getting the same error and I was hoping you had a solution.

**Comment by JacobGalati** [comment]
Nevermind, I figured it out. My version of sass-rails was too old.
