### ISSUE TITLE
SASSC?

### ISSUE THREAD

**Issue by nadnoslen** [stuyam/bootstrap-email#23]
I'm working in a new Rails 5.1 api app and went to install the sass gem.  It reminded me that:

> Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

Have you considered supporting the SASSC Engine?  I imagine we could configure this gem to use an environment variable to choose the engine?  I haven't checked this out yet, but I figured I'd report it.

Cheers.

(See: https://github.com/sass/sassc-ruby#readme)

**Comment by stuyam** [comment]
Thanks for bringing that up. You are right about that, we need to figure that out. Open to suggestions.

**Comment by nadnoslen** [comment]
Agreed 100% with @aaronchi.  I haven't had a chance to put a PR together.  Just looked quick at the code and I think we need to do a little `config`-dance to include the name of the engine you're compiling with and then alter the call here: 

```ruby
    def bootstrap_email_head
      html_string = <<-HEREDOC
        <style type="text/css">
          #{Sass::Engine.new(File.open(File.expand_path('../core/head.scss', __dir__)).read, {syntax: :scss, style: :compressed, cache: false, read_cache: false}).render}
        </style>
      HEREDOC
      html_string
    end
```
https://github.com/stuyam/bootstrap-email/blob/master/lib/bootstrap-email.rb#L65

The README should be updated as well.

**Comment by nadnoslen** [comment]
Awesome!  Thanks guys 👍🏼
