### ISSUE TITLE
Online editor not working

### ISSUE THREAD

**Issue by ralphk86** [stuyam/bootstrap-email#27]
The online editor at https://bootstrapemail.com/editor currently does not appear to be working. When clicking Rerender (even without changing the default email), the following error is returned, see also the screenshot: 
> The change you wanted was rejected.
> Maybe you tried to change something you didn't have access to.
> 
> If you are the application owner check the logs for more information.
![Screenshot 2019-04-14 at 11 16 30](https://user-images.githubusercontent.com/7864906/56090763-cd181380-5ea6-11e9-96b2-dc62030a4b95.png)

**Comment by stuyam** [comment]
I haven't been able to reproduce this error. Are you still seeing the issue?

**Comment by ralphk86** [comment]
Hi,
Yes, the isuse is still there for me. I tried Chrome and Safari, both normal and incognito, with and without adblock. Same issue in all cases, as posted initially.

**Comment by ralphk86** [comment]
Update: It seems to work on another machine without any issues.
So this might be a local problem rather than something wrong with the online editor.

**Comment by stuyam** [comment]
Ill do some investigating, thank for you the feedback Ill look into it 👍

**Comment by MinimalDigital** [comment]
I just had the same issue when using Safari on macOS. I then switched to Firefox and it was fine.

**Comment by OlegFedko** [comment]
The root cause of the issue is that 3rd-party cookies disabled.
If one enables cookies from bootstrap-email.herokuapp.com problem disappears.
