### ISSUE TITLE
Don't require Rails, don't require SCSS

### ISSUE THREAD

**Issue by mcandre** [stuyam/bootstrap-email#28]
bootstrap-email would be a lot more useful as a typical CDN'ed .css file to drop into our email templates, rather than this Rails + SCSS monstrosity

**Comment by stuyam** [comment]
Unfortunately that isn't how css in email works. Bootstrap email compiles the css and inlines the styles into your email as well as converts things to more email friendly things like tables for layout. Many email clients you can't use a remote css files nor will it even work without it being inlined as properties onto the elements themselves.

If you want to use a CSS CDN you can just use the Bootstrap one in your email. Bootstrap Email solves the other problems of that not working in many email clients.

You can also use the [online editor](https://bootstrapemail.com/editor) if you just want to compile one off emails. That will also make it a little more clear what Bootstrap Email does when it compiles.
