### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by hwhelchel** [stuyam/bootstrap-email#35]
Hey @stuyam 

Rails 6 was released yesterday. Do you know what if any changes need to be made to make the gem work in Rails 6? Thank you for your help and a great gem!

**Comment by hwhelchel** [comment]
If anyone wants to test this out in their app here's the PR https://github.com/stuyam/bootstrap-email/pull/36

I'm running it in rails 6 production and haven't hit any bugs or errors.

**Comment by stuyam** [comment]
#36 merged

**Comment by hwhelchel** [comment]
<img width="865" alt="Screen Shot 2019-08-20 at 12 44 56 PM" src="https://user-images.githubusercontent.com/4792375/63366722-586b4f00-c348-11e9-80ea-4ab26893e3aa.png">

Deploying master of the gem isn't working. Investigating.

**Comment by hwhelchel** [comment]
Deleted my `Gemfile.lock` and rebuilt it. I think the issue was just specific to me since I made the PR and bumped the version to `0.2.6` separately.
