### ISSUE TITLE
Undefined method add_child for nil

### ISSUE THREAD

**Issue by achaves06** [stuyam/bootstrap-email#39]
I'm getting the following error:

```
NoMethodError: undefined method `add_child' for nil:NilClass
2019-08-23T14:28:18.336Z 8932 TID-ounlng4rs WARN: /home/achaves/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootstrap-email-0.2.6/lib/bootstrap-email.rb:52:in `inject_head!'
/home/achaves/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootstrap-email-0.2.6/lib/bootstrap-email.rb:24:in `perform_full_compile'
/home/achaves/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootstrap-email-0.2.6/lib/bootstrap-email/action_mailer.rb:10:in `make_bootstrap_mail'
/mnt/c/Users/chave/Documents/apps/smarthost/app/mailers/user_mailer.rb:45:in `price_check_notification'
```

the mailer action looks like this:

```
def price_check_notification(email, user_name, property_id, property_name, impacted_dates)
    @property_name = property_name
    @impacted_dates = impacted_dates
    @user_name = user_name
    @property_id = property_id
    make_bootstrap_mail(:to => email,  subject: I18n.t(:prices_not_in_sync))
  end
```

Any ideas on what's causing this?

**Comment by JacobGalati** [comment]
I'm also seeing this issue.
`        3: from /Users/JacobG/.rvm/gems/ruby-2.3.1/gems/bootstrap-email-0.3.1/lib/bootstrap-email/action_mailer.rb:10:in `make_bootstrap_mail'
        2: from /Users/JacobG/.rvm/gems/ruby-2.3.1/gems/bootstrap-email-0.3.1/lib/bootstrap-email.rb:24:in `perform_full_compile'
        1: from /Users/JacobG/.rvm/gems/ruby-2.3.1/gems/bootstrap-email-0.3.1/lib/bootstrap-email.rb:52:in `inject_head!'
NoMethodError (undefined method `add_child' for nil:NilClass)`

**Comment by stuyam** [comment]
This is the line that is being run: 
```ruby
def inject_head!
  @doc.at_css('head').add_child(bootstrap_email_head)
end
```

This would mean to me that there is no `<head>` tag in your template. Ensure you are using the html template described here and that the file is named correctly: https://bootstrapemail.com/docs/setup.

**Comment by arthurtofani** [comment]
I had the same issue and it worked when I set my custom mailer class to the correct layout:
```ruby
class CustomDeviseMailer < Devise::Mailer
  layout 'mailer'
   # ...
end
```

**Comment by stuyam** [comment]
I updated the docs for setup to specify the `layout` and hopefully improving clarity.
