### ISSUE TITLE
CSS File Download option.

### ISSUE THREAD

**Issue by SteloNLD** [stuyam/bootstrap-email#4]
I need the precompiled CSS file, bootstrap-email.min.css for example.

**Comment by stuyam** [comment]
@SteloNLD can you tell me more about how you would use a precompiled CSS file without the rest of the library?

**Comment by SteloNLD** [comment]
@stuyam most of my Powershell scripts send email messages to the Servicedesk, Systems Administrator, Users and or Managers
For the styling i use [BootstrapForEmail](https://github.com/advancedrei/BootstrapForEmail/blob/master/Stylesheet/bootstrap-email.min.css)

While it still works great the last update for this file was on Sep 18 2012, so i am looking for a alternatieve.

**Comment by graham-sportsmgmt** [comment]
I'd like the raw css as well, we're using node.js in Azure Functions and really only need to include the base classes that we can edit down if necessary.  I'd be happy to work on a node solution for this, but would need to understand more about what is required.

**Comment by verysimplenick** [comment]
Hi, I want same : compile to an html, which I can use as a template. Not from ruby.
It's possible?

**Comment by stuyam** [comment]
@verysimplenick you can use the editor on: https://bootstrapemail.com/editor
It allows you to do just that, past in your bootstrap html and have it come out ready for email 👍

**Comment by stuyam** [comment]
As for getting raw css, the library wasn't built for that. The library works by compiling regular html into email friendly html. That includes converting some elements into tables, inlining css into elements, etc. If you just want to convert a simple template using this you can use the bootstrap email editor that runs bootstrap email compiler and can give you the raw html: https://bootstrapemail.com/editor

@graham-sportsmgmt yeah I would like to have implementations that work on more platforms and haven't gotten around to it yet. It would be awesome to make something that was 100% node that could run in something like rails or something else but haven't found anything to accomplish that. So the implementation is just for ruby on rails for the time being.
