### ISSUE TITLE
The online editor doesn't work with safari 12.1.2

### ISSUE THREAD

**Issue by davidglassborow** [stuyam/bootstrap-email#44]
Hi, great project.  I'm using .NET, so looking to do a one off conversion using the 
[online editor](https://bootstrapemail.com/editor) but when I hit Rerender, I get an error message:

    The change you wanted was rejected.
    Maybe you tried to change something you didn't have access to.
    If you are the application owner check the logs for more information.

Any ideas ?

**Comment by stuyam** [comment]
Sometimes weird things happen with it Im not sure why, testing now it seems to work fine for me in Chrome on Mac.

**Comment by davidglassborow** [comment]
Ahh looks like a Safari issue, Chrome works fine on my mac, thanks for the quick response !

**Comment by davidglassborow** [comment]
Closing this, changing title to help other people

**Comment by stuyam** [comment]
Good to know, thanks!
