### ISSUE TITLE
semicolon is missing

### ISSUE THREAD

**Issue by DimitriOstapenko** [stuyam/bootstrap-email#51]
semicolon is missing in core/sass/_variables.scss line 113

108   75: 75%,
109   100: 100%,
110   auto: auto
111 ) !default;
112 
113 $border-color: $gray-300 !default
114 
115 $table-accent-bg: #f2f2f2 !default;
116 $table-background-color: null !default;
117 $table-border-color: $border-color !default;
118 $table-border-width: $border-width !default;

**Comment by stuyam** [comment]
Fixed in latest release https://github.com/stuyam/bootstrap-email/releases/tag/0.3.1
