### ISSUE TITLE
Provide a test on the description page

### ISSUE THREAD

**Issue by ZenImagine** [stuyam/bootstrap-email#52]
Hi, thanks for integrating Bootstrap 4 with emails.

Can you put in the description of the program a test:
https://litmus.com/

Thank you

**Comment by stuyam** [comment]
The screenshots on the homepage of https://bootstrapemail.com are actual test, you can click the different email clients to see the results of the different tests, they were taken in Litmus. I can't afford to pay for Litmus indefinitely so I only used it for a short time.
