### ISSUE TITLE
The online editor cant render on Chrome

### ISSUE THREAD

**Issue by eladc1** [stuyam/bootstrap-email#55]
Using Chrome, even in an incognito session, when i try to render the code i get  an error message:

> The change you wanted was rejected.
> Maybe you tried to change something you didn't have access to.
> If you are the application owner check the logs for more information.

Even if i try to render the default code without touching the code.
On my friend PC right next to me, the editor works fine.
For me- works fine on Firefox.

Thanks!

**Comment by stuyam** [comment]
Related to #27

**Comment by eladc1** [comment]
true. closings.
