### ISSUE TITLE
Online editor throwing error ?

### ISSUE THREAD

**Issue by darxmac** [stuyam/bootstrap-email#58]
Hi, not sure if this is the right place, but the online editor at

https://bootstrapemail.com/editor

Throws this error when hitting the "re-render" button. Even with just the demo content without changes.

![Screenshot 2020-01-12 at 13 14 40](https://user-images.githubusercontent.com/139267/72218647-80e52700-353d-11ea-8f5d-1e3beafe69b3.png)

**Comment by stuyam** [comment]
Related: #27
