### ISSUE TITLE
bootstrapemail.com - Application Error

### ISSUE THREAD

**Issue by Staja** [stuyam/bootstrap-email#73]
https://bootstrapemail.com/editor

> **Application error**
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
> `heroku logs --tail`

**Comment by Staja** [comment]
Now located at https://editor.bootstrapemail.com/

**Comment by stuyam** [comment]
Good point I should set up a redirect, thanks. 👍
