### ISSUE TITLE
Why do I get a 404 for the documentation???

### ISSUE THREAD

**Issue by TMHDesign** [stuyam/bootstrap-email#75]
I signed into the editor via GitHub. The editor works fine, but when I click on documentation I get a 404 error

https://bootstrapemail.com/docs/introduction

404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by stuyam** [comment]
Working on migrating to a different docs repo as we speak. Bear with me 🙏  should be back up shortly

**Comment by stuyam** [comment]
Should be back up, thanks for your patience 👍
